export const initialGroups = [
  {
    id: 'research-lab',
    name: 'Research Lab',
    description: 'AI-grounded project discussion',
    members: 8,
    docs: 4,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    messages: 120,
    aiReady: true,
    tags: ['AI', 'NLP'],
    pinned: ['Research Plan', 'Model Notes'],
    recentFiles: ['paper.pdf', 'results.csv'],
    lastIndexed: Date.now() - 1000 * 60 * 3,
    contextHealthy: true,
  },
  {
    id: 'backend-team',
    name: 'Backend Team',
    description: 'REST, sockets, and storage',
    members: 14,
    docs: 12,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    messages: 487,
    aiReady: true,
    tags: ['Node', 'Express', 'MongoDB', 'Docker'],
    pinned: ['API Guidelines', 'Deployment Notes'],
    recentFiles: ['api_design.pdf', 'docker.pdf', 'roadmap.pdf'],
    lastIndexed: Date.now() - 1000 * 60 * 3,
    contextHealthy: true,
  },
  {
    id: 'placement-prep',
    name: 'Placement Prep',
    description: 'Interview prep and shared notes',
    members: 5,
    docs: 2,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    messages: 84,
    aiReady: false,
    tags: ['Interview', 'Notes'],
    pinned: ['Interview Tips'],
    recentFiles: ['questions.pdf'],
    lastIndexed: Date.now() - 1000 * 60 * 60,
    contextHealthy: false,
  },
  {
    id: 'system-design',
    name: 'System Design',
    description: 'Architecture and references',
    members: 9,
    docs: 6,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 200).toISOString(),
    messages: 220,
    aiReady: false,
    tags: ['Architecture'],
    pinned: ['Design Principles'],
    recentFiles: ['architecture.pdf'],
    lastIndexed: Date.now() - 1000 * 60 * 10,
    contextHealthy: true,
  },
  {
    id: 'operating-systems',
    name: 'Operating Systems',
    description: 'Revision docs and discussion',
    members: 6,
    docs: 3,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    messages: 45,
    aiReady: false,
    tags: ['OS', 'Systems'],
    pinned: [],
    recentFiles: ['notes.pdf'],
    lastIndexed: Date.now() - 1000 * 60 * 60 * 6,
    contextHealthy: true,
  },
];
