export const NOTIFICATION_CATEGORIES = Object.freeze({
	CHAT: 'chat',
	DOCUMENTS: 'documents',
	AI: 'ai',
	GROUP: 'group',
	SYSTEM: 'system',
});

export const NOTIFICATION_STATUS = Object.freeze({
	UNREAD: 'UNREAD',
	READ: 'READ',
	ARCHIVED: 'ARCHIVED',
});

export const NOTIFICATION_PRIORITY = Object.freeze({
	LOW: 'low',
	NORMAL: 'normal',
	HIGH: 'high',
	URGENT: 'urgent',
});

export const NOTIFICATION_TYPES = Object.freeze({
	// Chat
	MESSAGE: 'MESSAGE',
	MENTION: 'MENTION',
	REPLY: 'REPLY',
	REACTION: 'REACTION',

	// AI
	AI_RESPONSE: 'AI_RESPONSE',
	AI_CONFIGURATION_UPDATED: 'AI_CONFIGURATION_UPDATED',
	AI_PROCESSING_FAILED: 'AI_PROCESSING_FAILED',

	// Documents
	DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
	DOCUMENT_READY: 'DOCUMENT_READY',
	DOCUMENT_FAILED: 'DOCUMENT_FAILED',
	DOCUMENT_DELETED: 'DOCUMENT_DELETED',

	// Groups
	GROUP_CREATED: 'GROUP_CREATED',
	GROUP_UPDATED: 'GROUP_UPDATED',
	MEMBER_JOINED: 'MEMBER_JOINED',
	MEMBER_LEFT: 'MEMBER_LEFT',
	ROLE_CHANGED: 'ROLE_CHANGED',
	USER_REMOVED: 'USER_REMOVED',
});
