import { GROUP_ROLES } from './roles.js';

export const GROUP_PERMISSIONS = Object.freeze({
	MANAGE_GROUP: [GROUP_ROLES.OWNER, GROUP_ROLES.ADMIN],
	MANAGE_MEMBERS: [GROUP_ROLES.OWNER, GROUP_ROLES.ADMIN],
	MODERATE_MEMBERS: [GROUP_ROLES.OWNER, GROUP_ROLES.ADMIN, GROUP_ROLES.MODERATOR],
});
