name: Deploy

on:
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to AWS EC2
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Tested Commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Generate .env.server
        run: |
          cat > .env.server <<EOF
          NODE_ENV=production
          PORT=5000
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          IMAGEKIT_PUBLIC_KEY=${{ secrets.IMAGEKIT_PUBLIC_KEY }}
          IMAGEKIT_PRIVATE_KEY=${{ secrets.IMAGEKIT_PRIVATE_KEY }}
          IMAGEKIT_URL_ENDPOINT=${{ secrets.IMAGEKIT_URL_ENDPOINT }}
          GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
          GROQ_MODEL=${{ secrets.GROQ_MODEL }}
          CLIENT_URL=${{ secrets.CLIENT_URL }}
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          IMAGE_TAG=${{ github.event.workflow_run.head_sha }}
          EOF

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/collix.pem
          chmod 600 ~/.ssh/collix.pem

          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Create Deployment Directory
        env:
          EC2_USER: ${{ secrets.EC2_USERNAME }}
        run: |
          ssh -i ~/.ssh/collix.pem \
            ${EC2_USER}@${{ secrets.EC2_HOST }} \
            "
            sudo mkdir -p /opt/collix
            sudo chown -R ${EC2_USER}:${EC2_USER} /opt/collix
            "

      - name: Copy docker-compose
        run: |
          scp -i ~/.ssh/collix.pem \
            docker-compose.prod.yml \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/opt/collix/

      - name: Copy nginx configs
        run: |
          scp -i ~/.ssh/collix.pem -r \
            docker \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/opt/collix/

      - name: Copy scripts
        run: |
          scp -i ~/.ssh/collix.pem -r \
            scripts \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/opt/collix/

      - name: Copy environment
        run: |
          scp -i ~/.ssh/collix.pem \
            .env.server \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/opt/collix/

      - name: Deploy
        run: |
          ssh -i ~/.ssh/collix.pem \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} <<EOF

          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          export IMAGE_TAG=${{ github.event.workflow_run.head_sha }}

          cd /opt/collix

          chmod +x scripts/*.sh

          ./scripts/deploy.sh

          HEALTH_URL=http://localhost/api/v1/health \
          ./scripts/healthcheck.sh

          EOF